package company.vk.lection05.objects

enum class Strategies {
	SIMPLE_THREAD,
	SIMPLE_COROUTINE,
	SIMPLE_RX,
	SIMPLE_FLOW_APPENDING,
	SIMPLE_RX_APPENDING,
	LEGACY_NETWORK_COROUTINE,
	RETROFIT_NETWORK_COROUTINE
}